version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - postgres